//
//  KDChatConstant.h
//  kdweibo
//
//  Created by Guohuan Xu on 6/27/12.
//  Copyright (c) 2012 www.kingdee.com. All rights reserved.
//

#define CHAT_BUBBLE_VIEW_CREATED_LABEL_FONT_SIZE 12.0f
#define CHAT_BUBBLE_VIEW_CREAT_AT_LABEL_HEIGHT 16.0f

#define CHAT_BUBBLE_VIEW_CREAT_AT_LABEL_HEIGHT_AND_GAP_TOTAL 22.0f

#define CHAT_BUBBLE_WIDTH           (ScreenFullWidth - 32 - 8 - 20 - 20)
#define CHAT_BUBBLE_TEXT_WIDTH      168
#define CHAT_BUBBLE_TIMESTAMP_DIFF  (60 * 5)

#define CHAT_BUBBLE_DETAIL_BG_SHADOW_OFF_SET 2.0f

#define CHAT_BUBBLE_CELL_PICTURE_HEIGHT 100.0f

//默认字体的大小
#define CHAT_BUBBLE_CELL_DEFAULT_DIRECT_MESSAGE_FONT_SIZE 14.0f

#define CHAT_BUBBLE_CELL_DEFAULT_DIRECT_MESSAGE_TOP_GAP_TO_BG 5.0f

#define KD_CHAT_BUBBLE_VIEW_ADD_HALF_WIDTH 0
#define KD_CHAT_BUBBLE_VIEW_ADD_HALF_HEIGH 0

#define KD_CHAT_BUBBLE_VIEW_ADD_WIDTH (KD_CHAT_BUBBLE_VIEW_ADD_HALF_WIDTH * 2)
#define KD_CHAT_BUBBLE_VIEW_ADD_HEIGHT (KD_CHAT_BUBBLE_VIEW_ADD_HALF_HEIGH * 2)