//
//  BOSImageNames.h
//  Public
//
//  Created by Gil on 12-2-13.
//  Copyright (c) 2012年 Kingdee.com. All rights reserved.
//

#define IMAGE_BACKGROUND @"EMPCapture.bundle/background.png"
#define IMAGE_BACKGROUND_Phone5 @"EMPCapture.bundle/background-h568.png"
#define IMAGE_BG_TEXTFIELD @"EMPCapture.bundle/bg_textField.png"
#define IMAGE_BUTTONCUST @"EMPCapture.bundle/button_cust.png"
#define IMAGE_BUTTONCUST_HIGHLIGHT @"EMPCapture.bundle/button_cust_highlight.png"
#define IMAGE_BUTTONLOGIN @"EMPCapture.bundle/button_login.png"
#define IMAGE_BUTTONLOGIN_HIGHLIGHT @"EMPCapture.bundle/button_login_highlight.png"
#define IMAGE_BUTTONDEMO @"EMPCapture.bundle/button_demo.png"
#define IMAGE_BUTTONDEMO_HIGHLIGHT @"EMPCapture.bundle/button_demo_highlight.png"
#define IMAGE_ICONSECURITY @"EMPCapture.bundle/icon_security.png"
#define IMAGE_ICONAPPLICATION @"EMPCapture.bundle/icon_application.png"
#define IMAGE_LOGOKINGDEE @"EMPCapture.bundle/logo_kingdee.png"
#define IMAGE_BUTTON_SMS @"EMPCapture.bundle/button_sms.png"
#define IMAGE_BUTTON_SMS_HIGHLIGHT @"EMPCapture.bundle/button_sms_highlight.png"
#define IMAGE_BUTTON_SETUPPER @"EMPCapture.bundle/button_set_upper.png"
#define IMAGE_BUTTON_SETUPPER_HIGHLIGHT @"EMPCapture.bundle/button_set_upper_highlight.png"
#define IMAGE_BUTTON_SETMIDDLE @"EMPCapture.bundle/button_set_middle.png"
#define IMAGE_BUTTON_SETMIDDLE_HIGHLIGHT @"EMPCapture.bundle/button_set_middle_highlight.png"
#define IMAGE_BUTTON_SETBELOW @"EMPCapture.bundle/button_set_below.png"
#define IMAGE_BUTTON_SETBELOW_HIGHLIGHT @"EMPCapture.bundle/button_set_below_highlight.png"
#define IMAGE_BUTTON_SETLOGOUT @"EMPCapture.bundle/button_set_logout.png"
#define IMAGE_BUTTON_SETLOGOUT_HIGHLIGHT @"EMPCapture.bundle/button_set_logout_highlight.png"
#define IMAGE_BUTTON_SETUSER @"EMPCapture.bundle/button_set_user.png"
#define IMAGE_BACKGROUND_NAVBAR @"EMPCapture.bundle/background_nav_bar.png"
#define IMAGE_BUTTON_NAVBACK_HIGHLIGHT @"EMPCapture.bundle/button_nav_back_highlight.png"
#define IMAGE_BUTTON_NAVBACK @"EMPCapture.bundle/button_nav_back.png"
#define IMAGE_BUTTON_NAVDONE_HIGHLIGHT @"EMPCapture.bundle/button_nav_done_highlight.png"
#define IMAGE_BUTTON_NAVDONE @"EMPCapture.bundle/button_nav_done.png"
#define IMAGE_BUTTON_ABOUTLINE @"EMPCapture.bundle/button_about_line.png"

//FeedBack
#define IMAGE_FEEDBACK_BUBBLEMINE @"EMPCapture.bundle/feedback/bubbleMine.png"
#define IMAGE_FEEDBACK_BUBBLEMINE_HIGHLIGHT @"EMPCapture.bundle/feedback/bubbleMineHL.png"
#define IMAGE_FEEDBACK_BUBBLESOMEONE @"EMPCapture.bundle/feedback/bubbleSomeone.png"
#define IMAGE_FEEDBACK_BUBBLESOMEONE_HIGHLIGHT @"EMPCapture.bundle/feedback/bubbleSomeoneHL.png"
#define IMAGE_FEEDBACK_CHATVIEW_BG @"EMPCapture.bundle/feedback/chatView_bg.png"
#define IMAGE_FEEDBACK_DEL_SEND @"EMPCapture.bundle/feedback/del_send.png"
#define IMAGE_FEEDBACK_OPERATIONBOX_FAIL @"EMPCapture.bundle/feedback/operationbox_fail.jpg"
#define IMAGE_FEEDBACK_PICDOWNLOAD @"EMPCapture.bundle/feedback/pictureDownload.png"
#define IMAGE_FEEDBACK_RECORD01 @"EMPCapture.bundle/feedback/record01.png"
#define IMAGE_FEEDBACK_RECORD02 @"EMPCapture.bundle/feedback/record02.png"
#define IMAGE_FEEDBACK_RECORD03 @"EMPCapture.bundle/feedback/record03.png"
#define IMAGE_FEEDBACK_RECORD04 @"EMPCapture.bundle/feedback/record04.png"
#define IMAGE_FEEDBACK_RECORD05 @"EMPCapture.bundle/feedback/record05.png"
#define IMAGE_FEEDBACK_RECORD06 @"EMPCapture.bundle/feedback/record06.png"
#define IMAGE_FEEDBACK_RECORD07 @"EMPCapture.bundle/feedback/record07.png"
#define IMAGE_FEEDBACK_RECORDBTN @"EMPCapture.bundle/feedback/recordBtn.png"
#define IMAGE_FEEDBACK_RECORDBTN_HIGHLIGHT @"EMPCapture.bundle/feedback/recordBtn_highlight.png"
#define IMAGE_FEEDBACK_TOOLBAR_BG @"EMPCapture.bundle/feedback/toolBar_bg.png"
#define IMAGE_FEEDBACK_TOOLBAR_CAMERA @"EMPCapture.bundle/feedback/toolBar_camera.png"
#define IMAGE_FEEDBACK_TOOLBAR_DONE @"EMPCapture.bundle/feedback/toolBar_done.png"
#define IMAGE_FEEDBACK_TOOLBAR_SEND @"EMPCapture.bundle/feedback/toolBar_send.png"
#define IMAGE_FEEDBACK_TOOLBAR_TEXT @"EMPCapture.bundle/feedback/toolBar_text.png"
#define IMAGE_FEEDBACK_VOICEME1 @"EMPCapture.bundle/feedback/voice_me_1.png"
#define IMAGE_FEEDBACK_VOICEME2 @"EMPCapture.bundle/feedback/voice_me_2.png"
#define IMAGE_FEEDBACK_VOICEME3 @"EMPCapture.bundle/feedback/voice_me_3.png"
#define IMAGE_FEEDBACK_VOICEMEFULL @"EMPCapture.bundle/feedback/voice_me_full.png"
#define IMAGE_FEEDBACK_VOICEOTHER1 @"EMPCapture.bundle/feedback/voice_other_1.png"
#define IMAGE_FEEDBACK_VOICEOTHER2 @"EMPCapture.bundle/feedback/voice_other_2.png"
#define IMAGE_FEEDBACK_VOICEOTHER3 @"EMPCapture.bundle/feedback/voice_other_3.png"
#define IMAGE_FEEDBACK_VOICEOTHERFULL @"EMPCapture.bundle/feedback/voice_other_full.png"
#define IMAGE_FEEDBACK_VOICENODEUNREAD @"EMPCapture.bundle/feedback/VoiceNodeUnread.jpg"
#define IMAGE_FEEDBACK_TOUXIANG_BACKGROUND @"EMPCapture.bundle/feedback/touxiang_bg_small.png"
#define IMAGE_FEEDBACK_TOUXIANG @"EMPCapture.bundle/feedback/touxiang.png"

#define IMAGE_RECOMMEND_NEW @"EMPCapture.bundle/recommend/new.png"
#define IMAGE_RECOMMEND_BUTTON_TRY @"EMPCapture.bundle/recommend/button_try.png"
#define IMAGE_RECOMMEND_BUTTON_TRY_HIGHLIGHT @"EMPCapture.bundle/recommend/button_try_highlight.png"
#define IMAGE_RECOMMEND_APP_DEFAULT_ICON @"EMPCapture.bundle/recommend/app_default_icon.png"
